[package]
name = "tasks"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "crates/*"
]
exclude = [
    "plugins/file-note-provider"
]

[dependencies]
wasmtime = "32.0.0"
wasmtime-wasi = "32.0.0"
